spring.application.name=UberAuthService

spring.datasource.url=jdbc:mysql://localhost:3306/uber_db_local

spring.datasource.username=root

spring.datasource.password=Nasir@02

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=validate

server.port=7474

# to enable lazy loading in spring data jpa
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

logging.level.org.springframework.data=DEBUG

spring.flyway.url=jdbc:mysql://localhost:3306/uber_db_local

spring.flyway.user=root

spring.flyway.password=Nasir@02


spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

cookie.expiry=3600
jwt.expiry = 3600
jwt.secret = "uhuhgruihuigthguthgiuhioi6kholijoirjoithgiujpotigoihtgjfpo54t48u4t50p58tuirhj9u5op4t89ru5t[50-t98y8ruie09tryfui5-0t"